"""
Imoogle 5.0 Document Service
Create and export documents, summaries, and formatted content.
"""

from typing import Optional, Dict, Any
from io import BytesIO
from datetime import datetime


class DocumentService:
    """
    Document creation service:
    1. Generate formatted documents
    2. Create summaries
    3. Export to various formats
    """
    
    def __init__(self):
        pass
    
    async def create_text_document(
        self,
        title: str,
        content: str,
        author: str = "ImoogleAI",
    ) -> bytes:
        """Create a plain text document."""
        doc_content = f"""{'=' * 50}
{title.upper()}
{'=' * 50}

Author: {author}
Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}
Generated by: ImoogleAI

{'-' * 50}

{content}

{'-' * 50}
End of Document
"""
        return doc_content.encode('utf-8')
    
    async def create_markdown_document(
        self,
        title: str,
        content: str,
        author: str = "ImoogleAI",
        sections: list[Dict[str, str]] = None,
    ) -> bytes:
        """Create a markdown document."""
        doc_content = f"""# {title}

**Author:** {author}  
**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}  
**Generated by:** ImoogleAI

---

{content}
"""
        
        if sections:
            for section in sections:
                doc_content += f"\n## {section.get('heading', 'Section')}\n\n"
                doc_content += f"{section.get('content', '')}\n"
        
        doc_content += f"\n---\n*Document generated by ImoogleAI*"
        
        return doc_content.encode('utf-8')
    
    async def create_summary(
        self,
        text: str,
        max_sentences: int = 5,
    ) -> str:
        """Create a simple extractive summary."""
        # Split into sentences
        import re
        sentences = re.split(r'(?<=[.!?])\s+', text)
        
        if len(sentences) <= max_sentences:
            return text
        
        # Simple scoring based on length and position
        scored = []
        for i, sentence in enumerate(sentences):
            # Prefer longer sentences and those at the beginning
            score = len(sentence.split()) * (1 + 1/(i+1))
            scored.append((score, sentence))
        
        # Get top sentences
        scored.sort(reverse=True)
        top_sentences = [s[1] for s in scored[:max_sentences]]
        
        # Reorder by original position
        ordered = [s for s in sentences if s in top_sentences]
        
        return ' '.join(ordered)
    
    async def create_list_document(
        self,
        title: str,
        items: list[str],
        numbered: bool = True,
    ) -> str:
        """Create a formatted list."""
        content = f"**{title}**\n\n"
        
        for i, item in enumerate(items, 1):
            if numbered:
                content += f"{i}. {item}\n"
            else:
                content += f"- {item}\n"
        
        return content
    
    async def create_table(
        self,
        headers: list[str],
        rows: list[list[str]],
    ) -> str:
        """Create a markdown table."""
        if not headers or not rows:
            return ""
        
        # Calculate column widths
        widths = [len(h) for h in headers]
        for row in rows:
            for i, cell in enumerate(row):
                if i < len(widths):
                    widths[i] = max(widths[i], len(str(cell)))
        
        # Build table
        table = "| " + " | ".join(h.ljust(widths[i]) for i, h in enumerate(headers)) + " |\n"
        table += "|" + "|".join("-" * (w + 2) for w in widths) + "|\n"
        
        for row in rows:
            table += "| " + " | ".join(str(cell).ljust(widths[i]) for i, cell in enumerate(row)) + " |\n"
        
        return table
    
    async def format_conversation_export(
        self,
        messages: list[Dict[str, str]],
        user_name: str = "User",
    ) -> bytes:
        """Export conversation history as a document."""
        content = f"""# Conversation Export

**User:** {user_name}
**Exported:** {datetime.now().strftime('%Y-%m-%d %H:%M')}
**Total Messages:** {len(messages)}

---

"""
        
        for msg in messages:
            role = "You" if msg["role"] == "user" else "ImoogleAI"
            content += f"**{role}:**\n{msg['content']}\n\n"
        
        content += "---\n*Exported from ImoogleAI*"
        
        return content.encode('utf-8')
    
    def format_code_block(
        self,
        code: str,
        language: str = "",
    ) -> str:
        """Format code in a code block."""
        return f"```{language}\n{code}\n```"
    
    def format_quote(self, text: str) -> str:
        """Format text as a quote."""
        lines = text.split('\n')
        return '\n'.join(f"> {line}" for line in lines)


# Singleton instance
document_service = DocumentService()
